---
title: "HDT6_Mineria"
output: html_document
date: "2023-04-14"
---

```{r, echo=FALSE}
library(dplyr)
library(rpart)
library(rpart.plot)
library(caret)
library(tree)
library(randomForest)
library(ggplot2)
library(tidyr)
library(e1071)
library(caret)
library(dummy)
library(ModelMetrics)


datos <- read.csv("train.csv")
```

##Pregunta 1. Variables Dicotomicas

```{r}
datos$clasification <- ifelse(datos$SalePrice > 214000, "Caras", ifelse(datos$SalePrice>163000, "Intemedia", "Economicas"))

## Definicion de variables dicotomicas
datos['Econonmicas']<- ifelse(datos$SalePrice<163000,1,ifelse(datos$SalePrice>=163000 & datos$SalePrice<214000,0,0))
datos['Intermedia']<- ifelse(datos$SalePrice<163000,0,ifelse(datos$SalePrice>=163000 & datos$SalePrice<214000,1,0))
datos['Caras']<- ifelse(datos$SalePrice<163000,0,ifelse(datos$SalePrice>=163000 & datos$SalePrice<214000,0,1))

```

##Pregunta 2. Conjunto de entramiento y prueba

```{r}
porcentaje<-0.7
set.seed(123)
corte <- sample(nrow(datos),nrow(datos)*porcentaje)
training1<-datos[corte,]
test1<-datos[-corte,]

datos2 <- dplyr::select_if(datos, is.numeric)
datos2 <- na.omit(datos2)
datosc <- scale(datos2)
corte <- sample(nrow(datosc),nrow(datosc)*porcentaje)
training<-datosc[corte,]
test<-datosc[-corte,]

```


